const mongoose = require("mongoose");
const requireLogin = require("../middlewares/requireLogin");
const requireCredits = require("../middlewares/requireCredits");
const Mailer = require("../services/Mailer");

const surveyTemplate = require("../services/emailTemplates/surveyTemplate");

const Survey = mongoose.model("surveys"); //slightly different approach->instead of directly importing from the model js file

module.exports = (app) => {
  app.get("/api/surveys/thanks", (req, res) => {
    res.send("Thanks for your response!");
  });

  app.post("/api/surveys", requireLogin, requireCredits, async (req, res) => {
    //req.body includes title,subject,body,recipient lists
    const { title, subject, body, recipients } = req.body;

    const survey = new Survey({
      title,
      body,
      subject,
      recipients: recipients
        .split(",")
        .map((email) => ({ email: email.trim() })), //return an object, () is for clarity. When return for arrow function, you can choose to put ()
      _user: req.user.id, //this id is automatically generated by mongoose
      dateSent: Date.now(),
    });
    console.log("bye", survey);

    //Great Place to send an email
    const mailer = new Mailer(survey, surveyTemplate(survey));

    try {
      await mailer.send();
      //save to database
      await survey.save();
      req.user.credits -= 1;
      const user = await req.user.save();
      console.log("user:", user);

      res.send(user);
    } catch (err) {
      //422 - unprocessed entity - some problem with data
      res.status(422).send(err);
    }
  });
};
